{
  "openapi": "3.0.3",
  "info": {
    "title": "gLab Identity Service",
    "description": "JWT Identity Service for Galvanize Projects",
    "version": "1.0.0",
    "contact": {
      "name": "Rob Wing",
      "email": "rob.wing@galvanize.com"
    }
  },
  "servers": [
    {
      "description": "QA Deployment - Gateway",
      "url": "http://bakery.galvanizelabs.net"
    },
    {
      "description": "QA Deployment",
      "url": "http://identity.galvanizelabs.net"
    },
    {
      "description": "Development",
      "url": "http://localhost:9100"
    }
  ],
  "tags": [
    {"name": "Authorization", "description": "Username / Password authentication and authorization"},
    {"name": "Registration", "description": "User Registration"},
    {"name": "Admin", "description": "Resources for Administrators"}
  ],
  "paths": {
    "/api/auth/": {
      "post": {
        "tags": [
          "Authorization"
        ],
        "summary": "Login with username and password"
      }
    },
    "/api/account": {
      "get": {
        "tags": [
          "Registration"
        ],
        "description": "Display the current users login information"
      }
    },
    "/api/account/register": {
      "post": {
        "tags": [
          "Registration"
        ],
        "description": "User self registration"
      }
    },
    "/api/account/passwd": {
      "patch": {
        "tags": [
          "Registration"
        ],
        "description": "User change password",
        "security": [
          {
            "bearerAuth": ["ROLE_USER"]
          }
        ]
      }
    },
    "/api/admin/users/{username}": {
      "get": {
        "tags": ["Admin"],
        "summary": "Get a user's details",
        "security": [
          {
            "bearerAuth": ["ROLE_ADMIN"]
          }
        ]
      },
      "patch": {
        "tags": ["Admin"],
        "description": "Update Username, first, last, email, or password only",
        "security": [
          {
            "bearerAuth": ["ROLE_ADMIN"]
          }
        ]
      }
    },
    "/api/admin/roles": {
      "get": {
        "tags": ["Admin"],
        "summary": "List Roles",
        "operationId": "getRoles",
        "security": [
          {
            "bearerAuth": ["ROLE_ADMIN"]
          }
        ]
      },
      "post": {
        "tags": ["Admin"],
        "summary": "Add a new role",
        "operationId": "addNewRole",
        "security": [
          {
            "bearerAuth": ["ROLE_ADMIN"]
          }
        ]
      }
    },
    "/api/admin/roles/{role}": {
      "get": {
        "tags": ["Admin"],
        "summary": "List Role details with associated users",
        "operationId": "getRole",
        "security": [
          {
            "bearerAuth": ["ROLE_ADMIN"]
          }
        ]
      },
      "patch": {
        "tags": ["Admin"],
        "summary": "Update Role name or description",
        "operationId": "updateRole",
        "security": [
          {
            "bearerAuth": ["ROLE_ADMIN"]
          }
        ]
      },
      "delete": {
        "tags": ["Admin"],
        "summary": "Delete a role",
        "description": "Deletes a role with no assignments, otherwise, throws an error",
        "operationId": "deleteRole",
        "security": [
          {
            "bearerAuth": ["ROLE_ADMIN"]
          }
        ]
      }
    },
    "/api/admin/roles/{role}/{username}": {
      "put": {
        "tags": ["Admin"],
        "summary": "Add a user to a role",
        "description": "If the user already exists in the role, then it's still successful",
        "operationId": "addRoleUser",
        "security": [
          {
            "bearerAuth": ["ROLE_ADMIN"]
          }
        ]
      },
      "delete": {
        "tags": ["Admin"],
        "summary": "Remove user from role",
        "description": "Removes a user from this role, still successful if the user is not in the role",
        "operationId": "removeRoleUser",
        "security": [
          {
            "bearerAuth": ["ROLE_ADMIN"]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
